name: Node.js CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache dependencies
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: ${{runner.os}}-node_modules-${{hashFiles('package*.json')}}-${{hashFiles('.github/workflows/node.yml')}}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != true
        run: npm ci

      - name: Lint code
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present && find dist/main.js
